### ISSUE TITLE
Upon startup with web components, hooks error shows up

### ISSUE THREAD

**Issue by CodeByAlex** [AriPerkkio/storybook-addon-aria-live#3]
When using web components (at least thats what I'm using), when starting up with this addon included all stories show up like this:
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/29763590/167235502-c8ae66f3-3e07-44b2-8e0a-44df9ffdc598.png">

Error: "Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:"

version: 0.0.5
storybook version: 6.4.19
node: 14.18.0

Really excited about this addon because I think it could be really helpful! just cant get it up and running

**Comment by AriPerkkio** [comment]
Thanks for the report @CodeByAlex! I was able to reproduce this issue with a `@storybook/web-components` setup.

This is fixed in [0.0.6](https://www.npmjs.com/package/storybook-addon-aria-live/v/0.0.6) version!

**Comment by CodeByAlex** [comment]
Wow -This was really fast! Thanks!
