### ISSUE TITLE
Unable to use with Storybook 7

### ISSUE THREAD

**Issue by stuartjnelson** [AriPerkkio/storybook-addon-aria-live#6]
Hello,

I was interested in installing your integration. I got the following warning which I think is because we're using Storybook 7.

- Storybook: `7.0.12`
- Node: `16.13.2`
- OS: MacOS 13.5

![Screenshot 2023-09-07 at 10 32 41](https://github.com/AriPerkkio/storybook-addon-aria-live/assets/5795894/12d69f68-03b2-43ae-8745-2fc6797e7f25)

**Comment by AriPerkkio** [comment]
Thanks for the report, I'll need to update the `peerDependencies` to allow Storybook 7 as well. And do some testing with it.

Does it work if you install using `npm install -D --legacy-peer-deps storybook-addon-aria-live`?

**Comment by AriPerkkio** [comment]
@stuartjnelson This is now fixed and released in `0.1.0`: https://github.com/AriPerkkio/storybook-addon-aria-live/releases/tag/v0.1.0
